options {
  STATIC=false;
  BUILD_NODE_FILES = true;
  DEBUG_PARSER=true;
} 

PARSER_BEGIN(TRANSB)
import java.io.*;
import java.text.*;
import java.util.Queue;
import java.util.LinkedList;





 

public class TRANSB {

  public static void main(String[] args) throws ParseException, IOException {
    File inputFile = new File("doc2.txt");
    FileReader reader = new FileReader(inputFile);

    TRANSB parser = new TRANSB(reader);


   






    



    try {
    parser.TextDoc2();

      System.out.println("Valide");
    } catch (ParseException e) {
      System.err.println("PAS VALIDE");
    } 
  }
}

PARSER_END(TRANSB)

TOKEN : {
  < REEL: <ENTIER>","(<CHIFFRE>)+ >
  | < ENTIER: ("-")?(<CHIFFRE>)+ >
  | < COMMENT: "/*"(~[]|"\n")*"*/" >
  | <#CHIFFRE: ["0"-"9"] >


}


void TextDoc2() :
{}
{
  EnsembleLignes() | {}
}

void EnsembleLignes() :
{}
{
  MultilignesValides() SuitEnsble()
  | < COMMENT > SuitEnsble()
}

void SuitEnsble() :
{}
{
  EnsembleLignes() | {}
}

void MultilignesValides() :
{}
{
  LigneValide() SuitMultiligne()
}

void SuitMultiligne() :
{}
{
  MultilignesValides() | {}
}

void LigneValide() :
{}
{
  "@" Contenuligne() "\n"
}

void Contenuligne() :
{}
{
  Mots() SerieMots()
}

void SerieMots() :
{}
{
  Contenuligne() | {}
}

void Mots() :
{}
{
  < ENTIER >
  | < REEL >
}