/* Generated By:JavaCC: Do not edit this line. TRANSBConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TRANSBConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AT = 1;
  /** RegularExpression Id. */
  int PLUS = 2;
  /** RegularExpression Id. */
  int MINUS = 3;
  /** RegularExpression Id. */
  int COMMA = 4;
  /** RegularExpression Id. */
  int INT = 5;
  /** RegularExpression Id. */
  int REAL = 6;
  /** RegularExpression Id. */
  int COMMENT = 7;
  /** RegularExpression Id. */
  int WORD = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"@\"",
    "\"+\"",
    "\"-\"",
    "\",\"",
    "<INT>",
    "<REAL>",
    "<COMMENT>",
    "<WORD>",
    "\"\\n\"",
  };

}
