/* Generated By:JavaCC: Do not edit this line. TRANSBConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TRANSBConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int REEL = 1;
  /** RegularExpression Id. */
  int ENTIER = 2;
  /** RegularExpression Id. */
  int COMMENT = 3;
  /** RegularExpression Id. */
  int CHIFFRE = 4;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<REEL>",
    "<ENTIER>",
    "<COMMENT>",
    "<CHIFFRE>",
    "\"@\"",
    "\"\\n\"",
  };

}
